// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 获得系统信息接口
 * Input:
 * Output: dm 返回接口对象
 * Return:
 * Others:
 **/

public interface _Callback_IService_getSystemInformation extends Ice.TwowayCallback
{
    public void response(Result __ret, ISystemInformationPrx si);
}
