// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 获得设备状态
 * Input: 
 * Output: states 返回设备状态列表
 * Return:
 * Others: 将返回全部设备的运行状态
 **/

public interface _Callback_IDataMonitor_getDevicesState extends Ice.TwowayCallback
{
    public void response(Result __ret, DeviceInfo[] states);
}
