// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 查询系统日志
 * Input: devName 设备名
 * inId 查询位置，第一次调用此参数使用0，再次调用使用上次调用返回的outId参数
 * limit 查询数据帧的最大数量
 * Output: msgs 返回查询的数据帧内容，字符串的数组
 * outId 返回查询的ID
 * Return:
 * Others: 
 **/

public interface _Callback_IDataMonitor_querySystemLog extends Ice.TwowayCallback
{
    public void response(Result __ret, String[] msgs, int outId);
}
