// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public interface _IDataMonitorOperationsNC
{
    /**
     * Description: 获得设备状态
     * Input: 
     * Output: states 返回设备状态列表
     * Return:
     * Others: 将返回全部设备的运行状态
     **/
    Result getDevicesState(DeviceInfoListHolder states);

    /**
     * Description: 转换点名为点ID(使用ID可提高点查询效率)
     * Input: ptNames 点名列表
     * Output: ptIds 返回点ID列表，如ID为-1表示无此点
     * Return:
     * Others: 
     **/
    Result queryPointIds(String[] ptNames, PointIdListHolder ptIds);

    /**
     * Description: 使用点ID查询点的实时值
     * Input: ptIds 点ID列表
     * Output: values 点实时值列表
     * Return:
     * Others: 
     **/
    Result queryRealDatas(int[] ptIds, RvqtListHolder values);

    /**
     * Description: 查询设备的通信数据帧
     * Input: devName 设备名
     * inId 查询位置，第一次调用此参数使用0，再次调用使用上次调用返回的outId参数
     * limit 查询数据帧的最大数量
     * Output: msgs 返回查询的数据帧内容，字符串的数组
     * outId 返回查询的ID
     * Return:
     * Others: 
     **/
    Result queryDeviceDataFrames(String devName, int inId, int limit, StringListHolder msgs, Ice.IntHolder outId);

    /**
     * Description: 查询系统日志
     * Input: devName 设备名
     * inId 查询位置，第一次调用此参数使用0，再次调用使用上次调用返回的outId参数
     * limit 查询数据帧的最大数量
     * Output: msgs 返回查询的数据帧内容，字符串的数组
     * outId 返回查询的ID
     * Return:
     * Others: 
     **/
    Result querySystemLog(int inId, int limit, StringListHolder msgs, Ice.IntHolder outId);
}
