// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 启动单个设备
 * Input: deviceName设备名称
 * Output: 
 * Return:
 * Others: 如工程配置此设备为非激状态，启动将失败。
 **/

public abstract class Callback_ISystemControl_startDevice
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<Result>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        ISystemControlPrxHelper.__startDevice_completed(this, __result);
    }
}
