// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 使用点ID查询点的实时值
 * Input: ptIds 点ID列表
 * Output: values 点实时值列表
 * Return:
 * Others: 
 **/

public abstract class Callback_IDataMonitor_queryRealDatas
    extends IceInternal.TwowayCallback implements _Callback_IDataMonitor_queryRealDatas
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IDataMonitorPrxHelper.__queryRealDatas_completed(this, __result);
    }
}
