// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 从文件导入工程
 * Input: fileName 导入工程的文件名，全路径
 * Output: 
 * Return:
 * Others: 当前工程将被覆盖
 **/

public abstract class Callback_ISystemControl_importProject
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<Result>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        ISystemControlPrxHelper.__importProject_completed(this, __result);
    }
}
