// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 导出工程到文件
 * Input:
 * Output: fileName 导出后工程文件名，全路径
 * Return:
 * Others: 
 **/

public abstract class Callback_ISystemControl_exportProject
    extends IceInternal.TwowayCallback implements _Callback_ISystemControl_exportProject
{
    public final void __completed(Ice.AsyncResult __result)
    {
        ISystemControlPrxHelper.__exportProject_completed(this, __result);
    }
}
