// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

/**
 * Description: 转换点名为点ID(使用ID可提高点查询效率)
 * Input: ptNames 点名列表
 * Output: ptIds 返回点ID列表，如ID为-1表示无此点
 * Return:
 * Others: 
 **/

public abstract class Callback_IDataMonitor_queryPointIds
    extends IceInternal.TwowayCallback implements _Callback_IDataMonitor_queryPointIds
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IDataMonitorPrxHelper.__queryPointIds_completed(this, __result);
    }
}
