// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public final class IDataMonitorPrxHolder
{
    public
    IDataMonitorPrxHolder()
    {
    }

    public
    IDataMonitorPrxHolder(IDataMonitorPrx value)
    {
        this.value = value;
    }

    public IDataMonitorPrx value;
}
