// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public interface IServicePrx extends Ice.ObjectPrx
{
    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     **/
    public Result getSystemControl(ISystemControlPrxHolder sc);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     **/
    public Result getSystemControl(ISystemControlPrxHolder sc, java.util.Map<String, String> __ctx);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl();

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(java.util.Map<String, String> __ctx);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(Ice.Callback __cb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(Callback_IService_getSystemControl __cb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(java.util.Map<String, String> __ctx, Callback_IService_getSystemControl __cb);

    public interface FunctionalCallback_IService_getSystemControl_Response
    {
        void apply(Result __ret, ISystemControlPrx sc);
    }

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(FunctionalCallback_IService_getSystemControl_Response __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(FunctionalCallback_IService_getSystemControl_Response __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(java.util.Map<String, String> __ctx,
                                                  FunctionalCallback_IService_getSystemControl_Response __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemControl(java.util.Map<String, String> __ctx,
                                                  FunctionalCallback_IService_getSystemControl_Response __responseCb,
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Description: 获得系统控制接口
     * Input:
     * Output: sc 返回接口对象
     * Return:
     * Others:
     * @param __result The asynchronous result object.
     **/
    public Result end_getSystemControl(ISystemControlPrxHolder sc, Ice.AsyncResult __result);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     **/
    public Result getDataMonitor(IDataMonitorPrxHolder dm);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     **/
    public Result getDataMonitor(IDataMonitorPrxHolder dm, java.util.Map<String, String> __ctx);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor();

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(java.util.Map<String, String> __ctx);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(Ice.Callback __cb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(Callback_IService_getDataMonitor __cb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(java.util.Map<String, String> __ctx, Callback_IService_getDataMonitor __cb);

    public interface FunctionalCallback_IService_getDataMonitor_Response
    {
        void apply(Result __ret, IDataMonitorPrx dm);
    }

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(FunctionalCallback_IService_getDataMonitor_Response __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(FunctionalCallback_IService_getDataMonitor_Response __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(java.util.Map<String, String> __ctx,
                                                FunctionalCallback_IService_getDataMonitor_Response __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getDataMonitor(java.util.Map<String, String> __ctx,
                                                FunctionalCallback_IService_getDataMonitor_Response __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Description: 获得数据监视接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __result The asynchronous result object.
     **/
    public Result end_getDataMonitor(IDataMonitorPrxHolder dm, Ice.AsyncResult __result);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     **/
    public Result getSystemInformation(ISystemInformationPrxHolder si);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     **/
    public Result getSystemInformation(ISystemInformationPrxHolder si, java.util.Map<String, String> __ctx);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation();

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(java.util.Map<String, String> __ctx);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(Ice.Callback __cb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(Callback_IService_getSystemInformation __cb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(java.util.Map<String, String> __ctx, Callback_IService_getSystemInformation __cb);

    public interface FunctionalCallback_IService_getSystemInformation_Response
    {
        void apply(Result __ret, ISystemInformationPrx si);
    }

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(FunctionalCallback_IService_getSystemInformation_Response __responseCb,
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(FunctionalCallback_IService_getSystemInformation_Response __responseCb,
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                      IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(java.util.Map<String, String> __ctx,
                                                      FunctionalCallback_IService_getSystemInformation_Response __responseCb,
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getSystemInformation(java.util.Map<String, String> __ctx,
                                                      FunctionalCallback_IService_getSystemInformation_Response __responseCb,
                                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                      IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Description: 获得系统信息接口
     * Input:
     * Output: dm 返回接口对象
     * Return:
     * Others:
     * @param __result The asynchronous result object.
     **/
    public Result end_getSystemInformation(ISystemInformationPrxHolder si, Ice.AsyncResult __result);
}
