// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public interface ISystemControl extends Ice.Object,
                                        _ISystemControlOperations, _ISystemControlOperationsNC
{
    public static final String ice_staticId = "::YNRPC::ISystemControl";

    public static final long serialVersionUID = 1460153824L;
}
