// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public enum Quality implements java.io.Serializable
{
    
    QUNCERTAIN(0),
    
    QGOOD(1),
    
    QBAD(2),
    
    QTIMEOUT(3),
    
    QUNCONNECT(4);

    public int
    value()
    {
        return __value;
    }

    public static Quality
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return QUNCERTAIN;
        case 1:
            return QGOOD;
        case 2:
            return QBAD;
        case 3:
            return QTIMEOUT;
        case 4:
            return QUNCONNECT;
        }
        return null;
    }

    private
    Quality(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 4);
    }

    public static void
    __write(IceInternal.BasicStream __os, Quality __v)
    {
        if(__v == null)
        {
            __os.writeEnum(Quality.QUNCERTAIN.value(), 4);
        }
        else
        {
            __os.writeEnum(__v.value(), 4);
        }
    }

    public static Quality
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(4);
        return __validate(__v);
    }

    private static Quality
    __validate(int __v)
    {
        final Quality __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
