// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public enum RedundencyState implements java.io.Serializable
{
    
    UNCERTAIN(0),
    
    MASTER(1),
    
    STANDBY(2),
    
    SINGLE(3);

    public int
    value()
    {
        return __value;
    }

    public static RedundencyState
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return UNCERTAIN;
        case 1:
            return MASTER;
        case 2:
            return STANDBY;
        case 3:
            return SINGLE;
        }
        return null;
    }

    private
    RedundencyState(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 3);
    }

    public static void
    __write(IceInternal.BasicStream __os, RedundencyState __v)
    {
        if(__v == null)
        {
            __os.writeEnum(RedundencyState.UNCERTAIN.value(), 3);
        }
        else
        {
            __os.writeEnum(__v.value(), 3);
        }
    }

    public static RedundencyState
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(3);
        return __validate(__v);
    }

    private static RedundencyState
    __validate(int __v)
    {
        final RedundencyState __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
