// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public final class VariantInt16PrxHolder
{
    public
    VariantInt16PrxHolder()
    {
    }

    public
    VariantInt16PrxHolder(VariantInt16Prx value)
    {
        this.value = value;
    }

    public VariantInt16Prx value;
}
