// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RpcCommon.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package YNRPC;

public enum VarType implements java.io.Serializable
{
    
    VTEMPTY(0),
    
    VTBOOL(1),
    
    VTINT8(2),
    
    VTINT16(3),
    
    VTINT32(4),
    
    VTINT64(5),
    
    VTREAL32(6),
    
    VTREAL64(7),
    
    VTSTRING(8);

    public int
    value()
    {
        return __value;
    }

    public static VarType
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return VTEMPTY;
        case 1:
            return VTBOOL;
        case 2:
            return VTINT8;
        case 3:
            return VTINT16;
        case 4:
            return VTINT32;
        case 5:
            return VTINT64;
        case 6:
            return VTREAL32;
        case 7:
            return VTREAL64;
        case 8:
            return VTSTRING;
        }
        return null;
    }

    private
    VarType(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 8);
    }

    public static void
    __write(IceInternal.BasicStream __os, VarType __v)
    {
        if(__v == null)
        {
            __os.writeEnum(VarType.VTEMPTY.value(), 8);
        }
        else
        {
            __os.writeEnum(__v.value(), 8);
        }
    }

    public static VarType
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(8);
        return __validate(__v);
    }

    private static VarType
    __validate(int __v)
    {
        final VarType __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
